version: "3.7"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data:rw"

  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/bot:ro
    depends_on:
      - redis
