on:
  push:
    branches:
    - main
  pull_request:
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "./bot"
        version: "~= 23.0"
    
